bind 0.0.0.0
protected-mode yes
port 6379

appendonly yes
aof-use-rdb-preamble yes
stop-writes-on-bgsave-error yes

# Redis Stack modules are bundled in redis/redis-stack-server image.
# RediSearch + RedisJSON are available by default.
